# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_login.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(334, 490)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 332, 488))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(330, 120))
        self.widget_2.setObjectName("widget_2")
        self.label_login_logo = QtWidgets.QLabel(self.widget_2)
        self.label_login_logo.setGeometry(QtCore.QRect(150, 20, 50, 50))
        self.label_login_logo.setText("")
        self.label_login_logo.setPixmap(QtGui.QPixmap(":/img/logo2.png"))
        self.label_login_logo.setObjectName("label_login_logo")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(80, 80, 181, 41))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lable_login_exit = QtWidgets.QLabel(self.widget_2)
        self.lable_login_exit.setGeometry(QtCore.QRect(300, 10, 18, 18))
        self.lable_login_exit.setText("")
        self.lable_login_exit.setPixmap(QtGui.QPixmap(":/img/exit.png"))
        self.lable_login_exit.setObjectName("lable_login_exit")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(330, 360))
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 40, 243, 132))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.layoutWidget1)
        self.widget_4.setMinimumSize(QtCore.QSize(240, 50))
        self.widget_4.setObjectName("widget_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 10, 238, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setMinimumSize(QtCore.QSize(20, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/user.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit.setMinimumSize(QtCore.QSize(210, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.layoutWidget1)
        self.widget_5.setMinimumSize(QtCore.QSize(240, 50))
        self.widget_5.setObjectName("widget_5")
        self.layoutWidget3 = QtWidgets.QWidget(self.widget_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 10, 238, 32))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setMinimumSize(QtCore.QSize(20, 30))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/img/passwd.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(210, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addWidget(self.widget_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(120)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 240, 40))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget4 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 260, 238, 18))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line = QtWidgets.QFrame(self.layoutWidget4)
        self.line.setMinimumSize(QtCore.QSize(90, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setMinimumSize(QtCore.QSize(16, 16))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/img/cicle.png"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget4)
        self.line_2.setMinimumSize(QtCore.QSize(90, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.layoutWidget5 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(100, 310, 122, 14))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(60)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.verticalLayout_2.addWidget(self.widget_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "一键链接  全心服务"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入用户名"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "请输入密码"))
        self.checkBox.setText(_translate("Form", "记住密码"))
        self.label_5.setText(_translate("Form", "忘记密码"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.label_7.setText(_translate("Form", "注册"))
        self.label_8.setText(_translate("Form", "控制台"))


import login_rc
