# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window_v8.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1083, 698)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1078, 692))
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setMinimumSize(QtCore.QSize(200, 690))
        self.widget_6.setObjectName("widget_6")
        self.widget1 = QtWidgets.QWidget(self.widget_6)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 182, 670))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget2 = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget2.sizePolicy().hasHeightForWidth())
        self.widget2.setSizePolicy(sizePolicy)
        self.widget2.setMinimumSize(QtCore.QSize(180, 50))
        self.widget2.setObjectName("widget2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 32))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(150, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.widget2)
        self.widget_2 = QtWidgets.QWidget(self.widget1)
        self.widget_2.setMinimumSize(QtCore.QSize(180, 170))
        self.widget_2.setObjectName("widget_2")
        self.widget3 = QtWidgets.QWidget(self.widget_2)
        self.widget3.setGeometry(QtCore.QRect(10, 10, 152, 134))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setMinimumSize(QtCore.QSize(70, 70))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget3)
        self.label_3.setMinimumSize(QtCore.QSize(150, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget1)
        self.widget_3.setMinimumSize(QtCore.QSize(170, 380))
        self.widget_3.setObjectName("widget_3")
        self.listWidget = QtWidgets.QListWidget(self.widget_3)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 161, 360))
        self.listWidget.setMinimumSize(QtCore.QSize(150, 360))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget1)
        self.widget_4.setMinimumSize(QtCore.QSize(180, 50))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 161, 32))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(150, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.horizontalLayout_7.addWidget(self.widget_6)
        self.widget_10 = QtWidgets.QWidget(self.widget)
        self.widget_10.setMinimumSize(QtCore.QSize(870, 690))
        self.widget_10.setObjectName("widget_10")
        self.widget4 = QtWidgets.QWidget(self.widget_10)
        self.widget4.setGeometry(QtCore.QRect(10, 10, 851, 671))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.widget4)
        self.widget_5.setMinimumSize(QtCore.QSize(850, 50))
        self.widget_5.setObjectName("widget_5")
        self.widget5 = QtWidgets.QWidget(self.widget_5)
        self.widget5.setGeometry(QtCore.QRect(10, 10, 371, 32))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget5)
        self.label_5.setMinimumSize(QtCore.QSize(100, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget5)
        self.label_6.setMinimumSize(QtCore.QSize(100, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget5)
        self.label_7.setMinimumSize(QtCore.QSize(100, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.widget6 = QtWidgets.QWidget(self.widget_5)
        self.widget6.setGeometry(QtCore.QRect(720, 10, 119, 37))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget6)
        self.label_8.setMinimumSize(QtCore.QSize(35, 35))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget6)
        self.label_9.setMinimumSize(QtCore.QSize(35, 35))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget6)
        self.label_10.setMinimumSize(QtCore.QSize(35, 35))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.widget_7 = QtWidgets.QWidget(self.widget4)
        self.widget_7.setMinimumSize(QtCore.QSize(850, 550))
        self.widget_7.setObjectName("widget_7")
        self.layoutWidget_4 = QtWidgets.QWidget(self.widget_7)
        self.layoutWidget_4.setGeometry(QtCore.QRect(70, 10, 688, 72))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_22.setMinimumSize(QtCore.QSize(100, 30))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_5.setMinimumSize(QtCore.QSize(180, 30))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_23.setMinimumSize(QtCore.QSize(100, 30))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_6.setMinimumSize(QtCore.QSize(180, 30))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_6.addWidget(self.line_6)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_24.setMinimumSize(QtCore.QSize(100, 30))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_6.addWidget(self.label_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_19.setMinimumSize(QtCore.QSize(100, 30))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.line = QtWidgets.QFrame(self.layoutWidget_4)
        self.line.setMinimumSize(QtCore.QSize(180, 30))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_18.setMinimumSize(QtCore.QSize(100, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_5.addWidget(self.label_18)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_2.setMinimumSize(QtCore.QSize(180, 30))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_17.setMinimumSize(QtCore.QSize(100, 30))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setGeometry(QtCore.QRect(20, 100, 810, 430))
        self.widget_8.setMinimumSize(QtCore.QSize(810, 430))
        self.widget_8.setObjectName("widget_8")
        self.layoutWidget = QtWidgets.QWidget(self.widget_8)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 30, 288, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(200, 30))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setMinimumSize(QtCore.QSize(80, 30))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.verticalLayout_6.addWidget(self.widget_7)
        self.widget_9 = QtWidgets.QWidget(self.widget4)
        self.widget_9.setMinimumSize(QtCore.QSize(850, 50))
        self.widget_9.setObjectName("widget_9")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget_9)
        self.layoutWidget_3.setGeometry(QtCore.QRect(720, 10, 119, 37))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_25.setMinimumSize(QtCore.QSize(35, 35))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_8.addWidget(self.label_25)
        self.verticalLayout_6.addWidget(self.widget_9)
        self.horizontalLayout_7.addWidget(self.widget_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "111"))
        self.label_9.setText(_translate("Form", "111"))
        self.label_10.setText(_translate("Form", "111"))
        self.label_22.setText(_translate("Form", "TextLabel"))
        self.label_23.setText(_translate("Form", "TextLabel"))
        self.label_24.setText(_translate("Form", "TextLabel"))
        self.label_19.setText(_translate("Form", "TextLabel"))
        self.label_18.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "TextLabel"))
        self.label_20.setText(_translate("Form", "您当前没有可打包的游戏点击"))
        self.label_21.setText(_translate("Form", "创建游戏"))
        self.label_25.setText(_translate("Form", "111"))

